---
apiVersion: v1
kind: Pod
metadata:
  name: poc-locker
spec:
  containers:
    - name: caddy
      image: localhost/caddy:latest
      ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
      env:
        - name: CLOUDFLARE_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: secret
              key: CLOUDFLARE_API_TOKEN
      volumeMounts:
        - name: caddy-file
          mountPath: /etc/caddy/Caddyfile
          subPath: Caddyfile
        - name: caddy-data
          mountPath: /data
        - name: caddy-config
          mountPath: /config
    - name: filebrowser
      image: docker.io/filebrowser/filebrowser:v2
      args:
        - --port
        - "8082"
      ports:
        - containerPort: 8082
          hostPort: 8082
      volumeMounts:
        - name: filebrowser-data
          mountPath: /srv
        - name: filebrowser-database
          mountPath: /database
        - name: filebrowser-config
          mountPath: /config
    - name: vaultwarden
      image: docker.io/vaultwarden/server:1.36.0
      envFrom:
        - configMapRef:
            name: vaultwarden-env
      ports:
        - containerPort: 8081
          hostPort: 8081
          hostIP: 127.0.0.1
      volumeMounts:
        - name: vaultwarden-data
          mountPath: /data
    - name: dufs
      image: docker.io/sigoden/dufs:latest
      args: ["/data", "-A"]
      ports:
        - containerPort: 5000
      volumeMounts:
        - name: data-volume
          mountPath: /data
  volumes:
    - name: caddy-file
      configMap:
        name: caddyfile
    - name: caddy-data
      persistentVolumeClaim:
        claimName: caddy-data
    - name: caddy-config
      persistentVolumeClaim:
        claimName: caddy-config
    - name: filebrowser-data
      persistentVolumeClaim:
        claimName: filebrowser-data
    - name: filebrowser-database
      persistentVolumeClaim:
        claimName: filebrowser-database
    - name: filebrowser-config
      persistentVolumeClaim:
        claimName: filebrowser-config
    - name: vaultwarden-data
      persistentVolumeClaim:
        claimName: vaultwarden-data
    - name: data-volume
      persistentVolumeClaim:
        claimName: dufs-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddy-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddy-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dufs-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
